<GUI.Window>
  <W>1427.0</W>
  <H>793.0</H>
  <X>151.0</X>
  <Y>498.0</Y>
  <minimized>false</minimized>
  <maximized>NONE</maximized>
  <fullscreen>false</fullscreen>
  <resizable>true</resizable>
  <alwaysOnTop>false</alwaysOnTop>
  <layout-aggregator-type>GUI.LayoutAggregators.SwitchPane</layout-aggregator-type>
</GUI.Window>