<Layout.Layout>
  <id>b223206a-e59d-4470-bf1c-33114d48e047</id>
  <properties>
    <map>
      <entry>
        <string>padding</string>
        <double>0.0</double>
      </entry>
      <entry>
        <string>locked</string>
        <boolean>false</boolean>
      </entry>
    </map>
  </properties>
  <b>false</b>
  <child class="Layout.Widgets.EmptyWidget">
    <id>0fe300fb-08ac-4a6c-b988-7277a936c92f</id>
    <name></name>
    <configs class="empty-list"/>
  </child>
</Layout.Layout>