<Layout.Layout>
  <id>c6cb606a-9b71-455c-b21c-82ede378b675</id>
  <properties>
    <map>
      <entry>
        <string>padding</string>
        <double>0.0</double>
      </entry>
      <entry>
        <string>locked</string>
        <boolean>false</boolean>
      </entry>
    </map>
  </properties>
  <b>false</b>
  <child class="Layout.BiContainerPure">
    <id>caee8bc1-8ecc-47ed-9f05-cfb0cb78614b</id>
    <properties>
      <map>
        <entry>
          <string>col</string>
          <int>0</int>
        </entry>
        <entry>
          <string>orient</string>
          <javafx.geometry.Orientation>VERTICAL</javafx.geometry.Orientation>
        </entry>
        <entry>
          <string>pos</string>
          <double>0.5</double>
        </entry>
        <entry>
          <string>collap</string>
          <double>0.0</double>
        </entry>
        <entry>
          <string>abs_size</string>
          <boolean>false</boolean>
        </entry>
        <entry>
          <string>locked</string>
          <boolean>false</boolean>
        </entry>
      </map>
    </properties>
    <b>false</b>
    <children>
      <entry>
        <int>1</int>
        <Layout.UniContainer>
          <id>589066a4-38f3-4c6a-9432-753482555ae7</id>
          <properties>
            <map>
              <entry>
                <string>padding</string>
                <double>0.0</double>
              </entry>
              <entry>
                <string>locked</string>
                <boolean>false</boolean>
              </entry>
            </map>
          </properties>
          <b>false</b>
          <child class="Layout.BiContainerPure">
            <id>81d0ded1-e662-4562-abf3-30806f182c24</id>
            <properties>
              <map>
                <entry>
                  <string>col</string>
                  <int>0</int>
                </entry>
                <entry>
                  <string>orient</string>
                  <javafx.geometry.Orientation>VERTICAL</javafx.geometry.Orientation>
                </entry>
                <entry>
                  <string>pos</string>
                  <double>0.2622478386167147</double>
                </entry>
                <entry>
                  <string>collap</string>
                  <double>0.0</double>
                </entry>
                <entry>
                  <string>abs_size</string>
                  <boolean>false</boolean>
                </entry>
                <entry>
                  <string>locked</string>
                  <boolean>false</boolean>
                </entry>
              </map>
            </properties>
            <b>false</b>
            <children>
              <entry>
                <int>1</int>
                <Layout.UniContainer>
                  <id>87389173-c90a-4c2b-ba92-d56063ff5abc</id>
                  <properties>
                    <map>
                      <entry>
                        <string>padding</string>
                        <double>0.0</double>
                      </entry>
                      <entry>
                        <string>locked</string>
                        <boolean>false</boolean>
                      </entry>
                    </map>
                  </properties>
                  <b>false</b>
                  <child class="Layout.Widgets.FXMLWidget">
                    <id>f542323b-e149-4658-aa2e-ee740d90e7ec</id>
                    <name>PlayerControls</name>
                    <configs>
                      <Configuration.Config>
                        <gui__name>Is preferred</gui__name>
                        <name>preferred</name>
                        <value class="boolean">false</value>
                        <type>java.lang.Boolean</type>
                        <group>FXMLWidget</group>
                        <info>Preffered widget for its widget type.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Show chapters</gui__name>
                        <name>showChapters</name>
                        <value class="boolean">true</value>
                        <type>java.lang.Boolean</type>
                        <group>PlayerControlsController</group>
                        <info>Display chapter marks on seeker.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Show info for chapters</gui__name>
                        <name>popupChapters</name>
                        <value class="boolean">true</value>
                        <type>java.lang.Boolean</type>
                        <group>PlayerControlsController</group>
                        <info>Display pop up information for chapter marks on seeker.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Show elapsed time</gui__name>
                        <name>elapsedTime</name>
                        <value class="boolean">true</value>
                        <type>java.lang.Boolean</type>
                        <group>PlayerControlsController</group>
                        <info>Show elapsed time instead of remaining.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Play files on drop</gui__name>
                        <name>playDropped</name>
                        <value class="boolean">false</value>
                        <type>java.lang.Boolean</type>
                        <group>PlayerControlsController</group>
                        <info>Plays the drag and dropped files instead of enqueuing them in playlist.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                    </configs>
                  </child>
                </Layout.UniContainer>
              </entry>
              <entry>
                <int>2</int>
                <Layout.UniContainer>
                  <id>953d1dfd-0096-4a31-a8e1-e54d86e3e422</id>
                  <properties>
                    <map>
                      <entry>
                        <string>padding</string>
                        <double>0.0</double>
                      </entry>
                      <entry>
                        <string>locked</string>
                        <boolean>false</boolean>
                      </entry>
                    </map>
                  </properties>
                  <b>false</b>
                  <child class="Layout.BiContainerPure">
                    <id>068eee47-940d-4d55-85a6-9bef3ab6b1ca</id>
                    <properties>
                      <map>
                        <entry>
                          <string>col</string>
                          <int>0</int>
                        </entry>
                        <entry>
                          <string>orient</string>
                          <javafx.geometry.Orientation>HORIZONTAL</javafx.geometry.Orientation>
                        </entry>
                        <entry>
                          <string>pos</string>
                          <double>0.5</double>
                        </entry>
                        <entry>
                          <string>collap</string>
                          <double>0.0</double>
                        </entry>
                        <entry>
                          <string>abs_size</string>
                          <boolean>false</boolean>
                        </entry>
                        <entry>
                          <string>locked</string>
                          <boolean>false</boolean>
                        </entry>
                      </map>
                    </properties>
                    <b>false</b>
                    <children>
                      <entry>
                        <int>1</int>
                        <Layout.UniContainer>
                          <id>0e0df3be-0cfa-4d61-ac8d-cfbd8ce5f47e</id>
                          <properties>
                            <map>
                              <entry>
                                <string>padding</string>
                                <double>0.0</double>
                              </entry>
                              <entry>
                                <string>locked</string>
                                <boolean>false</boolean>
                              </entry>
                            </map>
                          </properties>
                          <b>false</b>
                          <child class="Layout.Widgets.ClassWidget">
                            <id>aab58e80-4b44-4808-b30d-5c01daa8808a</id>
                            <name>Settings</name>
                            <configs>
                              <Configuration.Config>
                                <gui__name>Is preferred</gui__name>
                                <name>preferred</name>
                                <value class="boolean">false</value>
                                <type>java.lang.Boolean</type>
                                <group>ClassWidget</group>
                                <info>Preffered widget for its widget type.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show non editable fields</gui__name>
                                <name>show_noneditable</name>
                                <value class="boolean">false</value>
                                <type>java.lang.Boolean</type>
                                <group>ConfiguratorComponent</group>
                                <info>Include non read-only fields.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Field names alignment</gui__name>
                                <name>alignemnt</name>
                                <value class="javafx.geometry.HPos">RIGHT</value>
                                <type>javafx.geometry.HPos</type>
                                <group>ConfiguratorComponent</group>
                                <info>Alignment of field names.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Group titles alignment</gui__name>
                                <name>title_align</name>
                                <value class="javafx.geometry.Pos">CENTER</value>
                                <type>javafx.geometry.Pos</type>
                                <group>ConfiguratorComponent</group>
                                <info>Alignment of group names.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>expanded</gui__name>
                                <name>expanded</name>
                                <value class="string">Shortcuts</value>
                                <type>java.lang.String</type>
                                <group>ConfiguratorComponent</group>
                                <info></info>
                                <editable>true</editable>
                                <visible>false</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                            </configs>
                            <class__type>Layout.WidgetImpl.ConfiguratorComponent</class__type>
                          </child>
                        </Layout.UniContainer>
                      </entry>
                      <entry>
                        <int>2</int>
                        <Layout.UniContainer>
                          <id>fba29436-13dd-4747-829b-210d4f74a085</id>
                          <properties>
                            <map>
                              <entry>
                                <string>padding</string>
                                <double>0.0</double>
                              </entry>
                              <entry>
                                <string>locked</string>
                                <boolean>false</boolean>
                              </entry>
                            </map>
                          </properties>
                          <b>false</b>
                          <child class="Layout.BiContainerPure">
                            <id>000ac15b-5e87-4825-a930-9b729cdeb12d</id>
                            <properties>
                              <map>
                                <entry>
                                  <string>col</string>
                                  <int>0</int>
                                </entry>
                                <entry>
                                  <string>orient</string>
                                  <javafx.geometry.Orientation>HORIZONTAL</javafx.geometry.Orientation>
                                </entry>
                                <entry>
                                  <string>pos</string>
                                  <double>0.3761467889908257</double>
                                </entry>
                                <entry>
                                  <string>collap</string>
                                  <double>0.0</double>
                                </entry>
                                <entry>
                                  <string>abs_size</string>
                                  <boolean>false</boolean>
                                </entry>
                                <entry>
                                  <string>locked</string>
                                  <boolean>false</boolean>
                                </entry>
                              </map>
                            </properties>
                            <b>false</b>
                            <children>
                              <entry>
                                <int>1</int>
                                <Layout.UniContainer>
                                  <id>769433c7-096b-4512-be01-0a75174aa893</id>
                                  <properties>
                                    <map>
                                      <entry>
                                        <string>padding</string>
                                        <double>0.0</double>
                                      </entry>
                                      <entry>
                                        <string>locked</string>
                                        <boolean>false</boolean>
                                      </entry>
                                    </map>
                                  </properties>
                                  <b>false</b>
                                  <child class="Layout.Widgets.FXMLWidget">
                                    <id>b13e23c3-4e2b-4e68-b06d-7d0fe33f0b55</id>
                                    <name>ImageViewer</name>
                                    <configs>
                                      <Configuration.Config>
                                        <gui__name>Is preferred</gui__name>
                                        <name>preferred</name>
                                        <value class="boolean">false</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FXMLWidget</group>
                                        <info>Preffered widget for its widget type.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Read Mode</gui__name>
                                        <name>readMode</name>
                                        <value class="PseudoObjects.ReadMode">PLAYING</value>
                                        <type>PseudoObjects.ReadMode</type>
                                        <group>ImageViewerController</group>
                                        <info>Source of data for the widget.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Read mode change on drag</gui__name>
                                        <name>changeReadModeOnTransfer</name>
                                        <value class="boolean">false</value>
                                        <type>java.lang.Boolean</type>
                                        <group>ImageViewerController</group>
                                        <info>Change read mode to CUSTOM when data are arbitrary added to widget.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show content when empty</gui__name>
                                        <name>keepContentOnEmpty</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>ImageViewerController</group>
                                        <info>Keep showing previous content when the widget should be empty.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Thumbnail size</gui__name>
                                        <name>thumbSize</name>
                                        <value class="double">70.0</value>
                                        <type>java.lang.Double</type>
                                        <group>ImageViewerController</group>
                                        <info>Size of the thumbnails.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Thumbnail gap</gui__name>
                                        <name>thumbGap</name>
                                        <value class="double">2.0</value>
                                        <type>java.lang.Double</type>
                                        <group>ImageViewerController</group>
                                        <info>Spacing between thumbnails</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Thumbnail load time</gui__name>
                                        <name>thumbnailReloadTime</name>
                                        <value class="long">100</value>
                                        <type>java.lang.Long</type>
                                        <group>ImageViewerController</group>
                                        <info>Delay between thumbnail loading. It is not recommended to load all thumbnails immediatelly after each other</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>File search depth</gui__name>
                                        <name>folderTreeDepth</name>
                                        <value class="int">1</value>
                                        <type>java.lang.Integer</type>
                                        <group>ImageViewerController</group>
                                        <info>Depth to search to for files in folders.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Slideshow reload time</gui__name>
                                        <name>slideshow_dur</name>
                                        <value class="double">15000.0</value>
                                        <type>java.lang.Double</type>
                                        <group>ImageViewerController</group>
                                        <info>Time between picture change.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Slideshow</gui__name>
                                        <name>slideshow_on</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>ImageViewerController</group>
                                        <info>Turn sldideshow on/off.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                    </configs>
                                  </child>
                                </Layout.UniContainer>
                              </entry>
                              <entry>
                                <int>2</int>
                                <Layout.UniContainer>
                                  <id>025073a5-1b34-4af6-9c50-bdfc4150240a</id>
                                  <properties>
                                    <map>
                                      <entry>
                                        <string>padding</string>
                                        <double>0.0</double>
                                      </entry>
                                      <entry>
                                        <string>locked</string>
                                        <boolean>false</boolean>
                                      </entry>
                                    </map>
                                  </properties>
                                  <b>false</b>
                                  <child class="Layout.Widgets.FXMLWidget">
                                    <id>caaf1912-195e-4cd1-8f09-5cc8007f1762</id>
                                    <name>FileInfo</name>
                                    <configs>
                                      <Configuration.Config>
                                        <gui__name>Is preferred</gui__name>
                                        <name>preferred</name>
                                        <value class="boolean">false</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FXMLWidget</group>
                                        <info>Preffered widget for its widget type.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Read mode</gui__name>
                                        <name>readMode</name>
                                        <value class="PseudoObjects.ReadMode">PLAYING</value>
                                        <type>PseudoObjects.ReadMode</type>
                                        <group>FileInfoController</group>
                                        <info>Source of data for the widget.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Column min width</gui__name>
                                        <name>minColumnWidth</name>
                                        <value class="double">150.0</value>
                                        <type>java.lang.Double</type>
                                        <group>FileInfoController</group>
                                        <info>Minimal width for field columns. Use -1 for automatic width</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Cover source</gui__name>
                                        <name>cover_source</name>
                                        <value class="AudioPlayer.tagging.Metadata$CoverSource">ANY</value>
                                        <type>AudioPlayer.tagging.Metadata$CoverSource</type>
                                        <group>FileInfoController</group>
                                        <info>Source for cover image.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Read mode change on drag</gui__name>
                                        <name>changeReadModeOnTransfer</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Change read mode to CUSTOM when data are arbitrary added to widget.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Rating editable</gui__name>
                                        <name>editableRating</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Allow change of rating.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Rating stars</gui__name>
                                        <name>maxRating</name>
                                        <value class="int">5</value>
                                        <type>java.lang.Integer</type>
                                        <group>FileInfoController</group>
                                        <info>Number of stars for rating. Rating value is recalculated accordingly.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Rating allow partial</gui__name>
                                        <name>partialRating</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Allow partial values for rating.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Rating react on hover</gui__name>
                                        <name>hoverRating</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Move rating according to mouse when hovering.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Rating zoom on hover</gui__name>
                                        <name>rating_zoom</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Rating zoom on hover.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Rating skin</gui__name>
                                        <name>rating_skin</name>
                                        <value class="string">file:/C:/Users/Plutonium_/Documents/NetBeansProjects/Player/external/controls/Rating/min.css</value>
                                        <type>java.lang.String</type>
                                        <group>FileInfoController</group>
                                        <info>Rating skin.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Overrun style</gui__name>
                                        <name>overrun_style</name>
                                        <value class="javafx.scene.control.OverrunStyle">ELLIPSIS</value>
                                        <type>javafx.scene.control.OverrunStyle</type>
                                        <group>FileInfoController</group>
                                        <info>Style of clipping fields&apos; text when outside of the area.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Display cover</gui__name>
                                        <name>showCover</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show cover.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Display fields</gui__name>
                                        <name>showFields</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show fields.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Display empty fields</gui__name>
                                        <name>showEmptyFields</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show empty fields.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Group fields</gui__name>
                                        <name>groupFields</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Separate fields by gap and group them..</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show title</gui__name>
                                        <name>showTitle</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show track</gui__name>
                                        <name>showtrack</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show disc</gui__name>
                                        <name>showdisc</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show artist</gui__name>
                                        <name>showartist</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show album artist</gui__name>
                                        <name>showalbum_artist</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show album</gui__name>
                                        <name>showalbum</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show year</gui__name>
                                        <name>showyear</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show genre</gui__name>
                                        <name>showgenre</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show composer</gui__name>
                                        <name>showcomposer</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show publisher</gui__name>
                                        <name>showpublisher</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show rating</gui__name>
                                        <name>showrating</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show playcount</gui__name>
                                        <name>showplaycount</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show comment</gui__name>
                                        <name>showcomment</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show category</gui__name>
                                        <name>showcategory</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show filesize</gui__name>
                                        <name>showfilesize</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show filename</gui__name>
                                        <name>showfilename</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show format</gui__name>
                                        <name>showformat</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show bitrate</gui__name>
                                        <name>showbitrate</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show encoding</gui__name>
                                        <name>showencoding</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show location</gui__name>
                                        <name>showlocation</name>
                                        <value class="boolean">true</value>
                                        <type>java.lang.Boolean</type>
                                        <group>FileInfoController</group>
                                        <info>Show this field.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                    </configs>
                                  </child>
                                </Layout.UniContainer>
                              </entry>
                            </children>
                          </child>
                        </Layout.UniContainer>
                      </entry>
                    </children>
                  </child>
                </Layout.UniContainer>
              </entry>
            </children>
          </child>
        </Layout.UniContainer>
      </entry>
      <entry>
        <int>2</int>
        <Layout.UniContainer>
          <id>275b52e7-c8aa-4a88-900c-439b56fb1106</id>
          <properties>
            <map>
              <entry>
                <string>padding</string>
                <double>0.0</double>
              </entry>
              <entry>
                <string>locked</string>
                <boolean>false</boolean>
              </entry>
            </map>
          </properties>
          <b>false</b>
          <child class="Layout.BiContainerPure">
            <id>05f50ada-55d9-4898-bda4-f08f3b05b60d</id>
            <properties>
              <map>
                <entry>
                  <string>col</string>
                  <int>0</int>
                </entry>
                <entry>
                  <string>orient</string>
                  <javafx.geometry.Orientation>HORIZONTAL</javafx.geometry.Orientation>
                </entry>
                <entry>
                  <string>pos</string>
                  <double>0.5</double>
                </entry>
                <entry>
                  <string>collap</string>
                  <double>0.0</double>
                </entry>
                <entry>
                  <string>abs_size</string>
                  <boolean>false</boolean>
                </entry>
                <entry>
                  <string>locked</string>
                  <boolean>false</boolean>
                </entry>
              </map>
            </properties>
            <b>false</b>
            <children>
              <entry>
                <int>1</int>
                <Layout.UniContainer>
                  <id>c803ec7f-1def-4650-8aac-092e96f12c69</id>
                  <properties>
                    <map>
                      <entry>
                        <string>padding</string>
                        <double>0.0</double>
                      </entry>
                      <entry>
                        <string>locked</string>
                        <boolean>false</boolean>
                      </entry>
                    </map>
                  </properties>
                  <b>false</b>
                  <child class="Layout.PolyContainer">
                    <id>22427eb8-e92b-4447-96bf-f81f568adcb4</id>
                    <properties>
                      <map>
                        <entry>
                          <string>padding</string>
                          <double>0.0</double>
                        </entry>
                        <entry>
                          <string>locked</string>
                          <boolean>false</boolean>
                        </entry>
                        <entry>
                          <string>selected</string>
                          <int>-1</int>
                        </entry>
                      </map>
                    </properties>
                    <b>false</b>
                    <children/>
                  </child>
                </Layout.UniContainer>
              </entry>
              <entry>
                <int>2</int>
                <Layout.UniContainer>
                  <id>7c4f8f01-4243-4abc-b675-ed8074377d61</id>
                  <properties>
                    <map>
                      <entry>
                        <string>padding</string>
                        <double>0.0</double>
                      </entry>
                      <entry>
                        <string>locked</string>
                        <boolean>false</boolean>
                      </entry>
                    </map>
                  </properties>
                  <b>false</b>
                  <child class="Layout.Widgets.FXMLWidget">
                    <id>3d56c250-3ffc-40ba-a936-41d517ed47c6</id>
                    <name>Playlist</name>
                    <configs>
                      <Configuration.Config>
                        <gui__name>Is preferred</gui__name>
                        <name>preferred</name>
                        <value class="boolean">false</value>
                        <type>java.lang.Boolean</type>
                        <group>FXMLWidget</group>
                        <info>Preffered widget for its widget type.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Table orientation</gui__name>
                        <name>table_orient</name>
                        <value class="javafx.geometry.NodeOrientation">INHERIT</value>
                        <type>javafx.geometry.NodeOrientation</type>
                        <group>PlaylistController</group>
                        <info>Orientation of table.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Table text orientation</gui__name>
                        <name>cell_align</name>
                        <value class="javafx.geometry.Pos">CENTER_LEFT</value>
                        <type>javafx.geometry.Pos</type>
                        <group>PlaylistController</group>
                        <info>Orientation of text within table cells.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Zeropad numbers</gui__name>
                        <name>zeropad</name>
                        <value class="boolean">false</value>
                        <type>java.lang.Boolean</type>
                        <group>PlaylistController</group>
                        <info>Adds 0 to uphold number length consistency.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Show table menu button</gui__name>
                        <name>show_menu_button</name>
                        <value class="boolean">true</value>
                        <type>java.lang.Boolean</type>
                        <group>PlaylistController</group>
                        <info>Show table menu button for controlling columns.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Show table header</gui__name>
                        <name>show_header</name>
                        <value class="boolean">true</value>
                        <type>java.lang.Boolean</type>
                        <group>PlaylistController</group>
                        <info>Show table header with columns.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Search show always</gui__name>
                        <name>always_show_search</name>
                        <value class="boolean">false</value>
                        <type>java.lang.Boolean</type>
                        <group>PlaylistController</group>
                        <info>Forbid hiding of the search paneat all times. It will always be displayed.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Search hide always</gui__name>
                        <name>always_hide_search</name>
                        <value class="boolean">false</value>
                        <type>java.lang.Boolean</type>
                        <group>PlaylistController</group>
                        <info>Allows hiding search pane even if in effect.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Search ignore case</gui__name>
                        <name>ignoreCase</name>
                        <value class="boolean">true</value>
                        <type>java.lang.Boolean</type>
                        <group>PlaylistController</group>
                        <info>Ignore case when comparing for search results.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Search show original index</gui__name>
                        <name>orig_index</name>
                        <value class="boolean">true</value>
                        <type>java.lang.Boolean</type>
                        <group>PlaylistController</group>
                        <info>Show index of the itme as it was in the unfiltered playlisteven when filter applied.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                    </configs>
                  </child>
                </Layout.UniContainer>
              </entry>
            </children>
          </child>
        </Layout.UniContainer>
      </entry>
    </children>
  </child>
</Layout.Layout>