<Layout.Layout>
  <id>9609ba2e-c985-4bbd-b459-14301bc88fec</id>
  <properties>
    <map>
      <entry>
        <string>locked</string>
        <boolean>false</boolean>
      </entry>
    </map>
  </properties>
  <child class="Layout.Layout">
    <id>6e107fe0-d304-421a-a25c-5561d2d72d27</id>
    <properties>
      <map>
        <entry>
          <string>locked</string>
          <boolean>false</boolean>
        </entry>
      </map>
    </properties>
    <child class="Layout.BiContainer">
      <id>06af41b6-123c-41aa-b8a0-a75ae59e74fd</id>
      <properties>
        <map>
          <entry>
            <string>orient</string>
            <javafx.geometry.Orientation>HORIZONTAL</javafx.geometry.Orientation>
          </entry>
          <entry>
            <string>pos</string>
            <double>0.581353919239905</double>
          </entry>
          <entry>
            <string>collap</string>
            <double>0.0</double>
          </entry>
          <entry>
            <string>lock</string>
            <boolean>false</boolean>
          </entry>
        </map>
      </properties>
      <children>
        <entry>
          <int>1</int>
          <Layout.UniContainer>
            <id>af22013a-87b2-4eb8-b495-5b1fb10f6d83</id>
            <properties>
              <map/>
            </properties>
            <child class="Layout.BiContainer">
              <id>7550f4e2-38a2-4a7c-bdbf-396d7efd2b32</id>
              <properties>
                <map>
                  <entry>
                    <string>orient</string>
                    <javafx.geometry.Orientation>VERTICAL</javafx.geometry.Orientation>
                  </entry>
                  <entry>
                    <string>pos</string>
                    <double>0.34831460674157305</double>
                  </entry>
                  <entry>
                    <string>collap</string>
                    <double>0.0</double>
                  </entry>
                  <entry>
                    <string>lock</string>
                    <boolean>false</boolean>
                  </entry>
                </map>
              </properties>
              <children>
                <entry>
                  <int>1</int>
                  <Layout.UniContainer>
                    <id>a7b61a3c-efed-4f70-b62a-0389b7335240</id>
                    <properties>
                      <map/>
                    </properties>
                    <child class="Layout.ClassWidget">
                      <id>4a457f9d-6746-4893-b493-dc341e1d110a</id>
                      <name>Settings</name>
                      <configs>
                        <Configuration.Config>
                          <gui__name>Is preferred</gui__name>
                          <name>preferred</name>
                          <value class="boolean">false</value>
                          <type>java.lang.Boolean</type>
                          <group>ClassWidget</group>
                          <info>Preffered widget for its widget type.</info>
                          <editable>true</editable>
                          <visible>true</visible>
                          <min>NaN</min>
                          <max>NaN</max>
                        </Configuration.Config>
                        <Configuration.Config>
                          <gui__name>Show non editable fields</gui__name>
                          <name>show_noneditable</name>
                          <value class="boolean">false</value>
                          <type>java.lang.Boolean</type>
                          <group>ConfiguratorComponent</group>
                          <info>Include non read-only fields.</info>
                          <editable>true</editable>
                          <visible>true</visible>
                          <min>NaN</min>
                          <max>NaN</max>
                        </Configuration.Config>
                        <Configuration.Config>
                          <gui__name>Field names alignment</gui__name>
                          <name>alignemnt</name>
                          <value class="javafx.geometry.HPos">RIGHT</value>
                          <type>javafx.geometry.HPos</type>
                          <group>ConfiguratorComponent</group>
                          <info>Alignment of field names.</info>
                          <editable>true</editable>
                          <visible>true</visible>
                          <min>NaN</min>
                          <max>NaN</max>
                        </Configuration.Config>
                        <Configuration.Config>
                          <gui__name>Group titles alignment</gui__name>
                          <name>title_align</name>
                          <value class="javafx.geometry.Pos">CENTER</value>
                          <type>javafx.geometry.Pos</type>
                          <group>ConfiguratorComponent</group>
                          <info>Alignment of group names.</info>
                          <editable>true</editable>
                          <visible>true</visible>
                          <min>NaN</min>
                          <max>NaN</max>
                        </Configuration.Config>
                        <Configuration.Config>
                          <gui__name>expanded</gui__name>
                          <name>expanded</name>
                          <value class="string">GUI</value>
                          <type>java.lang.String</type>
                          <group>ConfiguratorComponent</group>
                          <info></info>
                          <editable>true</editable>
                          <visible>false</visible>
                          <min>NaN</min>
                          <max>NaN</max>
                        </Configuration.Config>
                      </configs>
                      <class__type>GUI.Components.ConfiguratorComponent</class__type>
                    </child>
                  </Layout.UniContainer>
                </entry>
                <entry>
                  <int>2</int>
                  <Layout.UniContainer>
                    <id>fe8656c0-b58b-46dd-a0b5-ffaf6d161059</id>
                    <properties>
                      <map/>
                    </properties>
                    <child class="Layout.BiContainer">
                      <id>2922fdfe-0f13-4bfd-8af0-aaae852ecb3a</id>
                      <properties>
                        <map>
                          <entry>
                            <string>orient</string>
                            <javafx.geometry.Orientation>VERTICAL</javafx.geometry.Orientation>
                          </entry>
                          <entry>
                            <string>pos</string>
                            <double>0.28027681660899656</double>
                          </entry>
                          <entry>
                            <string>collap</string>
                            <double>0.0</double>
                          </entry>
                          <entry>
                            <string>lock</string>
                            <boolean>false</boolean>
                          </entry>
                        </map>
                      </properties>
                      <children>
                        <entry>
                          <int>1</int>
                          <Layout.UniContainer>
                            <id>b3ed0386-7935-43f0-b318-2b2cdd27d307</id>
                            <properties>
                              <map/>
                            </properties>
                            <child class="Layout.FXMLWidget">
                              <id>b2ce81b2-162f-4fc1-a165-e6cb9df0faae</id>
                              <name>PlayerControls</name>
                              <configs>
                                <Configuration.Config>
                                  <gui__name>Is preferred</gui__name>
                                  <name>preferred</name>
                                  <value class="boolean">false</value>
                                  <type>java.lang.Boolean</type>
                                  <group>FXMLWidget</group>
                                  <info>Preffered widget for its widget type.</info>
                                  <editable>true</editable>
                                  <visible>true</visible>
                                  <min>NaN</min>
                                  <max>NaN</max>
                                </Configuration.Config>
                                <Configuration.Config>
                                  <gui__name>Show chapters</gui__name>
                                  <name>showChapters</name>
                                  <value class="boolean">true</value>
                                  <type>java.lang.Boolean</type>
                                  <group>PlayerControlsController</group>
                                  <info>Display chapter marks on seeker.</info>
                                  <editable>true</editable>
                                  <visible>true</visible>
                                  <min>NaN</min>
                                  <max>NaN</max>
                                </Configuration.Config>
                                <Configuration.Config>
                                  <gui__name>Show info for chapters</gui__name>
                                  <name>popupChapters</name>
                                  <value class="boolean">true</value>
                                  <type>java.lang.Boolean</type>
                                  <group>PlayerControlsController</group>
                                  <info>Display pop up information for chapter marks on seeker.</info>
                                  <editable>true</editable>
                                  <visible>true</visible>
                                  <min>NaN</min>
                                  <max>NaN</max>
                                </Configuration.Config>
                                <Configuration.Config>
                                  <gui__name>Show elapsed time</gui__name>
                                  <name>elapsedTime</name>
                                  <value class="boolean">true</value>
                                  <type>java.lang.Boolean</type>
                                  <group>PlayerControlsController</group>
                                  <info>Show elapsed time instead of remaining.</info>
                                  <editable>true</editable>
                                  <visible>true</visible>
                                  <min>NaN</min>
                                  <max>NaN</max>
                                </Configuration.Config>
                              </configs>
                              <fxmlUrl>file:/C:/Users/Plutonium_/Documents/NetBeansProjects/Player/properties/Widgets/PlayerControls.fxml</fxmlUrl>
                            </child>
                          </Layout.UniContainer>
                        </entry>
                        <entry>
                          <int>2</int>
                          <Layout.UniContainer>
                            <id>94d307b9-3170-44b1-b618-fa5834e95cef</id>
                            <properties>
                              <map/>
                            </properties>
                            <child class="Layout.Layout">
                              <id>bb398698-7725-4c2d-b5b3-989d69bf7152</id>
                              <properties>
                                <map>
                                  <entry>
                                    <string>locked</string>
                                    <boolean>false</boolean>
                                  </entry>
                                </map>
                              </properties>
                              <child class="Layout.FXMLWidget">
                                <id>f8161535-ec89-4269-b426-745e8b0c4ed6</id>
                                <name>ExtendedInfo</name>
                                <configs>
                                  <Configuration.Config>
                                    <gui__name>Is preferred</gui__name>
                                    <name>preferred</name>
                                    <value class="boolean">false</value>
                                    <type>java.lang.Boolean</type>
                                    <group>FXMLWidget</group>
                                    <info>Preffered widget for its widget type.</info>
                                    <editable>true</editable>
                                    <visible>true</visible>
                                    <min>NaN</min>
                                    <max>NaN</max>
                                  </Configuration.Config>
                                  <Configuration.Config>
                                    <gui__name>Read Mode</gui__name>
                                    <name>readMode</name>
                                    <value class="PseudoObjects.ReadMode">PLAYING</value>
                                    <type>PseudoObjects.ReadMode</type>
                                    <group>ExtendedInfoController</group>
                                    <info>Source of data for the widget.</info>
                                    <editable>true</editable>
                                    <visible>true</visible>
                                    <min>NaN</min>
                                    <max>NaN</max>
                                  </Configuration.Config>
                                  <Configuration.Config>
                                    <gui__name>Show Zero/End chapters</gui__name>
                                    <name>includeStartEndChapter</name>
                                    <value class="boolean">true</value>
                                    <type>java.lang.Boolean</type>
                                    <group>ExtendedInfoController</group>
                                    <info>Automatically add chapters at start and end of the song.</info>
                                    <editable>true</editable>
                                    <visible>true</visible>
                                    <min>NaN</min>
                                    <max>NaN</max>
                                  </Configuration.Config>
                                </configs>
                                <fxmlUrl>file:/C:/Users/Plutonium_/Documents/NetBeansProjects/Player/properties/Widgets/ExtendedInfo.fxml</fxmlUrl>
                              </child>
                            </child>
                          </Layout.UniContainer>
                        </entry>
                      </children>
                    </child>
                  </Layout.UniContainer>
                </entry>
              </children>
            </child>
          </Layout.UniContainer>
        </entry>
        <entry>
          <int>2</int>
          <Layout.UniContainer>
            <id>39aa6132-8260-40ba-a4d3-7529e877b72d</id>
            <properties>
              <map/>
            </properties>
            <child class="Layout.FXMLWidget">
              <id>20442baf-ffa5-4beb-bc70-5afd79f8f07a</id>
              <name>Playlist</name>
              <configs>
                <Configuration.Config>
                  <gui__name>Is preferred</gui__name>
                  <name>preferred</name>
                  <value class="boolean">false</value>
                  <type>java.lang.Boolean</type>
                  <group>FXMLWidget</group>
                  <info>Preffered widget for its widget type.</info>
                  <editable>true</editable>
                  <visible>true</visible>
                  <min>NaN</min>
                  <max>NaN</max>
                </Configuration.Config>
                <Configuration.Config>
                  <gui__name>Table orientation</gui__name>
                  <name>table_orient</name>
                  <value class="javafx.geometry.NodeOrientation">INHERIT</value>
                  <type>javafx.geometry.NodeOrientation</type>
                  <group>PlaylistController</group>
                  <info>Orientation of table.</info>
                  <editable>true</editable>
                  <visible>true</visible>
                  <min>NaN</min>
                  <max>NaN</max>
                </Configuration.Config>
                <Configuration.Config>
                  <gui__name>Table text orientation</gui__name>
                  <name>cell_align</name>
                  <value class="javafx.geometry.Pos">CENTER_LEFT</value>
                  <type>javafx.geometry.Pos</type>
                  <group>PlaylistController</group>
                  <info>Orientation of text within table cells.</info>
                  <editable>true</editable>
                  <visible>true</visible>
                  <min>NaN</min>
                  <max>NaN</max>
                </Configuration.Config>
                <Configuration.Config>
                  <gui__name>Zeropad numbers</gui__name>
                  <name>zeropad</name>
                  <value class="boolean">false</value>
                  <type>java.lang.Boolean</type>
                  <group>PlaylistController</group>
                  <info>Adds 0 to uphold number length consistency.</info>
                  <editable>true</editable>
                  <visible>true</visible>
                  <min>NaN</min>
                  <max>NaN</max>
                </Configuration.Config>
                <Configuration.Config>
                  <gui__name>Show table menu button</gui__name>
                  <name>show_menu_button</name>
                  <value class="boolean">true</value>
                  <type>java.lang.Boolean</type>
                  <group>PlaylistController</group>
                  <info>Show table menu button for controlling columns.</info>
                  <editable>true</editable>
                  <visible>true</visible>
                  <min>NaN</min>
                  <max>NaN</max>
                </Configuration.Config>
                <Configuration.Config>
                  <gui__name>Show table header</gui__name>
                  <name>show_header</name>
                  <value class="boolean">true</value>
                  <type>java.lang.Boolean</type>
                  <group>PlaylistController</group>
                  <info>Show table header with columns.</info>
                  <editable>true</editable>
                  <visible>true</visible>
                  <min>NaN</min>
                  <max>NaN</max>
                </Configuration.Config>
                <Configuration.Config>
                  <gui__name>Default open location</gui__name>
                  <name>browse</name>
                  <value class="string"></value>
                  <type>java.lang.String</type>
                  <group>PlaylistController</group>
                  <info>Opens this location for file dialogs.</info>
                  <editable>true</editable>
                  <visible>true</visible>
                  <min>NaN</min>
                  <max>NaN</max>
                </Configuration.Config>
                <Configuration.Config>
                  <gui__name>File search depth</gui__name>
                  <name>folder_depth</name>
                  <value class="int">1</value>
                  <type>java.lang.Integer</type>
                  <group>PlaylistController</group>
                  <info>Depth for recursive file search for folders.</info>
                  <editable>true</editable>
                  <visible>true</visible>
                  <min>NaN</min>
                  <max>NaN</max>
                </Configuration.Config>
              </configs>
              <fxmlUrl>file:/C:/Users/Plutonium_/Documents/NetBeansProjects/Player/properties/Widgets/Playlist.fxml</fxmlUrl>
            </child>
          </Layout.UniContainer>
        </entry>
      </children>
    </child>
  </child>
</Layout.Layout>