<Layout.Layout>
  <id>91bc2141-dc3e-448b-876e-57874dc5be4f</id>
  <properties>
    <map>
      <entry>
        <string>padding</string>
        <double>0.0</double>
      </entry>
      <entry>
        <string>locked</string>
        <boolean>false</boolean>
      </entry>
    </map>
  </properties>
  <b>false</b>
  <child class="Layout.BiContainerPure">
    <id>ede495d5-f44b-4ea5-8e5b-9383278d675c</id>
    <properties>
      <map>
        <entry>
          <string>col</string>
          <int>0</int>
        </entry>
        <entry>
          <string>orient</string>
          <javafx.geometry.Orientation>VERTICAL</javafx.geometry.Orientation>
        </entry>
        <entry>
          <string>pos</string>
          <double>0.4379263301500682</double>
        </entry>
        <entry>
          <string>collap</string>
          <double>0.0</double>
        </entry>
        <entry>
          <string>abs_size</string>
          <boolean>true</boolean>
        </entry>
        <entry>
          <string>locked</string>
          <boolean>false</boolean>
        </entry>
      </map>
    </properties>
    <b>false</b>
    <children>
      <entry>
        <int>1</int>
        <Layout.UniContainer>
          <id>2436b8bd-fc58-4083-b47e-a167dd8befd8</id>
          <properties>
            <map>
              <entry>
                <string>padding</string>
                <double>0.0</double>
              </entry>
              <entry>
                <string>locked</string>
                <boolean>false</boolean>
              </entry>
            </map>
          </properties>
          <b>false</b>
          <child class="Layout.BiContainerPure">
            <id>b33263dc-8cab-4680-9b17-dbf561c28035</id>
            <properties>
              <map>
                <entry>
                  <string>col</string>
                  <int>0</int>
                </entry>
                <entry>
                  <string>orient</string>
                  <javafx.geometry.Orientation>VERTICAL</javafx.geometry.Orientation>
                </entry>
                <entry>
                  <string>pos</string>
                  <double>0.26898047722342733</double>
                </entry>
                <entry>
                  <string>collap</string>
                  <double>0.0</double>
                </entry>
                <entry>
                  <string>abs_size</string>
                  <boolean>false</boolean>
                </entry>
                <entry>
                  <string>locked</string>
                  <boolean>false</boolean>
                </entry>
              </map>
            </properties>
            <b>false</b>
            <children>
              <entry>
                <int>1</int>
                <Layout.UniContainer>
                  <id>d6335941-8779-4307-b9b6-4a0bea89682f</id>
                  <properties>
                    <map>
                      <entry>
                        <string>padding</string>
                        <double>1.0</double>
                      </entry>
                      <entry>
                        <string>locked</string>
                        <boolean>false</boolean>
                      </entry>
                    </map>
                  </properties>
                  <b>false</b>
                  <child class="Layout.Widgets.FXMLWidget">
                    <id>823cff32-7418-4981-9da0-5f30cd3f0fc3</id>
                    <name>PlayerControls</name>
                    <configs>
                      <Configuration.Config>
                        <gui__name>Is preferred</gui__name>
                        <name>preferred</name>
                        <value class="boolean">false</value>
                        <type>java.lang.Boolean</type>
                        <group>FXMLWidget</group>
                        <info>Preffered widget for its widget type.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Show chapters</gui__name>
                        <name>showChapters</name>
                        <value class="boolean">true</value>
                        <type>java.lang.Boolean</type>
                        <group>PlayerControlsController</group>
                        <info>Display chapter marks on seeker.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Show info for chapters</gui__name>
                        <name>popupChapters</name>
                        <value class="boolean">true</value>
                        <type>java.lang.Boolean</type>
                        <group>PlayerControlsController</group>
                        <info>Display pop up information for chapter marks on seeker.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Show elapsed time</gui__name>
                        <name>elapsedTime</name>
                        <value class="boolean">true</value>
                        <type>java.lang.Boolean</type>
                        <group>PlayerControlsController</group>
                        <info>Show elapsed time instead of remaining.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                    </configs>
                  </child>
                </Layout.UniContainer>
              </entry>
              <entry>
                <int>2</int>
                <Layout.UniContainer>
                  <id>2f2fe8d7-cc0a-4fbb-8eed-03f6c47c97c9</id>
                  <properties>
                    <map>
                      <entry>
                        <string>padding</string>
                        <double>0.0</double>
                      </entry>
                      <entry>
                        <string>locked</string>
                        <boolean>false</boolean>
                      </entry>
                    </map>
                  </properties>
                  <b>false</b>
                  <child class="Layout.BiContainerPure">
                    <id>59e0116b-e521-46c7-b482-638f285056a9</id>
                    <properties>
                      <map>
                        <entry>
                          <string>col</string>
                          <int>0</int>
                        </entry>
                        <entry>
                          <string>orient</string>
                          <javafx.geometry.Orientation>HORIZONTAL</javafx.geometry.Orientation>
                        </entry>
                        <entry>
                          <string>pos</string>
                          <double>0.6379477250726041</double>
                        </entry>
                        <entry>
                          <string>collap</string>
                          <double>0.0</double>
                        </entry>
                        <entry>
                          <string>abs_size</string>
                          <boolean>false</boolean>
                        </entry>
                        <entry>
                          <string>locked</string>
                          <boolean>false</boolean>
                        </entry>
                      </map>
                    </properties>
                    <b>false</b>
                    <children>
                      <entry>
                        <int>1</int>
                        <Layout.UniContainer>
                          <id>fe24739d-277a-4e93-99cb-96f2079cf754</id>
                          <properties>
                            <map>
                              <entry>
                                <string>padding</string>
                                <double>0.0</double>
                              </entry>
                              <entry>
                                <string>locked</string>
                                <boolean>false</boolean>
                              </entry>
                            </map>
                          </properties>
                          <b>false</b>
                          <child class="Layout.BiContainerPure">
                            <id>e20c28a9-cc5b-4fda-aede-3711690d2545</id>
                            <properties>
                              <map>
                                <entry>
                                  <string>col</string>
                                  <int>0</int>
                                </entry>
                                <entry>
                                  <string>orient</string>
                                  <javafx.geometry.Orientation>HORIZONTAL</javafx.geometry.Orientation>
                                </entry>
                                <entry>
                                  <string>pos</string>
                                  <double>0.7427701674277016</double>
                                </entry>
                                <entry>
                                  <string>collap</string>
                                  <double>0.0</double>
                                </entry>
                                <entry>
                                  <string>abs_size</string>
                                  <boolean>false</boolean>
                                </entry>
                                <entry>
                                  <string>locked</string>
                                  <boolean>false</boolean>
                                </entry>
                              </map>
                            </properties>
                            <b>false</b>
                            <children>
                              <entry>
                                <int>1</int>
                                <Layout.UniContainer>
                                  <id>d0f19166-6e35-4041-b841-08d0510010b0</id>
                                  <properties>
                                    <map>
                                      <entry>
                                        <string>padding</string>
                                        <double>0.0</double>
                                      </entry>
                                      <entry>
                                        <string>locked</string>
                                        <boolean>false</boolean>
                                      </entry>
                                    </map>
                                  </properties>
                                  <b>false</b>
                                  <child class="Layout.Widgets.ClassWidget">
                                    <id>190b5c10-02a3-4ba5-bc1e-4b6fc913a967</id>
                                    <name>Settings</name>
                                    <configs>
                                      <Configuration.Config>
                                        <gui__name>Is preferred</gui__name>
                                        <name>preferred</name>
                                        <value class="boolean">false</value>
                                        <type>java.lang.Boolean</type>
                                        <group>ClassWidget</group>
                                        <info>Preffered widget for its widget type.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Show non editable fields</gui__name>
                                        <name>show_noneditable</name>
                                        <value class="boolean">false</value>
                                        <type>java.lang.Boolean</type>
                                        <group>ConfiguratorComponent</group>
                                        <info>Include non read-only fields.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Field names alignment</gui__name>
                                        <name>alignemnt</name>
                                        <value class="javafx.geometry.HPos">RIGHT</value>
                                        <type>javafx.geometry.HPos</type>
                                        <group>ConfiguratorComponent</group>
                                        <info>Alignment of field names.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>Group titles alignment</gui__name>
                                        <name>title_align</name>
                                        <value class="javafx.geometry.Pos">CENTER</value>
                                        <type>javafx.geometry.Pos</type>
                                        <group>ConfiguratorComponent</group>
                                        <info>Alignment of group names.</info>
                                        <editable>true</editable>
                                        <visible>true</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                      <Configuration.Config>
                                        <gui__name>expanded</gui__name>
                                        <name>expanded</name>
                                        <value class="string">GUI</value>
                                        <type>java.lang.String</type>
                                        <group>ConfiguratorComponent</group>
                                        <info></info>
                                        <editable>true</editable>
                                        <visible>false</visible>
                                        <min>NaN</min>
                                        <max>NaN</max>
                                      </Configuration.Config>
                                    </configs>
                                    <class__type>Layout.WidgetImpl.ConfiguratorComponent</class__type>
                                  </child>
                                </Layout.UniContainer>
                              </entry>
                              <entry>
                                <int>2</int>
                                <Layout.UniContainer>
                                  <id>d35d19fd-8471-47f2-816d-43e197b27d29</id>
                                  <properties>
                                    <map>
                                      <entry>
                                        <string>padding</string>
                                        <double>0.0</double>
                                      </entry>
                                      <entry>
                                        <string>locked</string>
                                        <boolean>false</boolean>
                                      </entry>
                                    </map>
                                  </properties>
                                  <b>true</b>
                                  <child class="Layout.Widgets.EmptyWidget">
                                    <id>1a766b3c-8d95-47b2-bf6a-055ca51d61ee</id>
                                    <name></name>
                                    <configs class="empty-list"/>
                                  </child>
                                </Layout.UniContainer>
                              </entry>
                            </children>
                          </child>
                        </Layout.UniContainer>
                      </entry>
                      <entry>
                        <int>2</int>
                        <Layout.UniContainer>
                          <id>418add09-d627-4b4f-bd82-3caa93fe508b</id>
                          <properties>
                            <map>
                              <entry>
                                <string>padding</string>
                                <double>0.0</double>
                              </entry>
                              <entry>
                                <string>locked</string>
                                <boolean>false</boolean>
                              </entry>
                            </map>
                          </properties>
                          <b>false</b>
                          <child class="Layout.Widgets.FXMLWidget">
                            <id>9acab229-e1e4-40a2-ba08-54481a66cb18</id>
                            <name>FileInfo</name>
                            <configs>
                              <Configuration.Config>
                                <gui__name>Is preferred</gui__name>
                                <name>preferred</name>
                                <value class="boolean">false</value>
                                <type>java.lang.Boolean</type>
                                <group>FXMLWidget</group>
                                <info>Preffered widget for its widget type.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Read mode</gui__name>
                                <name>readMode</name>
                                <value class="PseudoObjects.ReadMode">PLAYING</value>
                                <type>PseudoObjects.ReadMode</type>
                                <group>FileInfoController</group>
                                <info>Source of data for the widget.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Column min width</gui__name>
                                <name>minColumnWidth</name>
                                <value class="double">150.0</value>
                                <type>java.lang.Double</type>
                                <group>FileInfoController</group>
                                <info>Minimal width for field columns. Use -1 for automatic width</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Cover source</gui__name>
                                <name>cover_source</name>
                                <value class="AudioPlayer.tagging.Metadata$CoverSource">ANY</value>
                                <type>AudioPlayer.tagging.Metadata$CoverSource</type>
                                <group>FileInfoController</group>
                                <info>Source for cover image.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Read mode change on drag</gui__name>
                                <name>changeReadModeOnTransfer</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Change read mode to CUSTOM when data are arbitrary added to widget.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Rating editable</gui__name>
                                <name>editableRating</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Allow change of rating.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Rating stars</gui__name>
                                <name>maxRating</name>
                                <value class="int">5</value>
                                <type>java.lang.Integer</type>
                                <group>FileInfoController</group>
                                <info>Number of stars for rating. Rating value is recalculated accordingly.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Rating allow partial</gui__name>
                                <name>partialRating</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Allow partial values for rating.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Rating react on hover</gui__name>
                                <name>hoverRating</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Move rating according to mouse when hovering.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Rating zoom on hover</gui__name>
                                <name>rating_zoom</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Rating zoom on hover.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Rating skin</gui__name>
                                <name>rating_skin</name>
                                <value class="string">file:/C:/Users/Plutonium_/Documents/NetBeansProjects/Player/external/controls/Rating/min.css</value>
                                <type>java.lang.String</type>
                                <group>FileInfoController</group>
                                <info>Rating skin.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Overrun style</gui__name>
                                <name>overrun_style</name>
                                <value class="javafx.scene.control.OverrunStyle">ELLIPSIS</value>
                                <type>javafx.scene.control.OverrunStyle</type>
                                <group>FileInfoController</group>
                                <info>Style of clipping fields&apos; text when outside of the area.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Display cover</gui__name>
                                <name>showCover</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show cover.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Display fields</gui__name>
                                <name>showFields</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show fields.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Display empty fields</gui__name>
                                <name>showEmptyFields</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show empty fields.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Group fields</gui__name>
                                <name>groupFields</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Separate fields by gap and group them..</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show title</gui__name>
                                <name>showTitle</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show track</gui__name>
                                <name>showtrack</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show disc</gui__name>
                                <name>showdisc</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show artist</gui__name>
                                <name>showartist</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show album artist</gui__name>
                                <name>showalbum_artist</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show album</gui__name>
                                <name>showalbum</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show year</gui__name>
                                <name>showyear</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show genre</gui__name>
                                <name>showgenre</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show composer</gui__name>
                                <name>showcomposer</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show publisher</gui__name>
                                <name>showpublisher</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show rating</gui__name>
                                <name>showrating</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show playcount</gui__name>
                                <name>showplaycount</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show comment</gui__name>
                                <name>showcomment</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show category</gui__name>
                                <name>showcategory</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show filesize</gui__name>
                                <name>showfilesize</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show filename</gui__name>
                                <name>showfilename</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show format</gui__name>
                                <name>showformat</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show bitrate</gui__name>
                                <name>showbitrate</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show encoding</gui__name>
                                <name>showencoding</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                              <Configuration.Config>
                                <gui__name>Show location</gui__name>
                                <name>showlocation</name>
                                <value class="boolean">true</value>
                                <type>java.lang.Boolean</type>
                                <group>FileInfoController</group>
                                <info>Show this field.</info>
                                <editable>true</editable>
                                <visible>true</visible>
                                <min>NaN</min>
                                <max>NaN</max>
                              </Configuration.Config>
                            </configs>
                          </child>
                        </Layout.UniContainer>
                      </entry>
                    </children>
                  </child>
                </Layout.UniContainer>
              </entry>
            </children>
          </child>
        </Layout.UniContainer>
      </entry>
      <entry>
        <int>2</int>
        <Layout.UniContainer>
          <id>8aa6a0b2-99d5-4779-b69a-c6a8c3bb8f94</id>
          <properties>
            <map>
              <entry>
                <string>padding</string>
                <double>0.0</double>
              </entry>
              <entry>
                <string>locked</string>
                <boolean>false</boolean>
              </entry>
            </map>
          </properties>
          <b>false</b>
          <child class="Layout.BiContainerPure">
            <id>4f525388-73e9-4924-9fef-e478157bf985</id>
            <properties>
              <map>
                <entry>
                  <string>col</string>
                  <int>0</int>
                </entry>
                <entry>
                  <string>orient</string>
                  <javafx.geometry.Orientation>HORIZONTAL</javafx.geometry.Orientation>
                </entry>
                <entry>
                  <string>pos</string>
                  <double>0.5530253741054001</double>
                </entry>
                <entry>
                  <string>collap</string>
                  <double>0.0</double>
                </entry>
                <entry>
                  <string>abs_size</string>
                  <boolean>false</boolean>
                </entry>
                <entry>
                  <string>locked</string>
                  <boolean>false</boolean>
                </entry>
              </map>
            </properties>
            <b>false</b>
            <children>
              <entry>
                <int>1</int>
                <Layout.UniContainer>
                  <id>4af0e50b-c292-4c59-a909-71cea47538a7</id>
                  <properties>
                    <map>
                      <entry>
                        <string>padding</string>
                        <double>0.0</double>
                      </entry>
                      <entry>
                        <string>locked</string>
                        <boolean>false</boolean>
                      </entry>
                    </map>
                  </properties>
                  <b>false</b>
                </Layout.UniContainer>
              </entry>
              <entry>
                <int>2</int>
                <Layout.UniContainer>
                  <id>9d70bdb6-2919-41e7-a372-e42f6c8ff629</id>
                  <properties>
                    <map>
                      <entry>
                        <string>padding</string>
                        <double>0.0</double>
                      </entry>
                      <entry>
                        <string>locked</string>
                        <boolean>false</boolean>
                      </entry>
                    </map>
                  </properties>
                  <b>false</b>
                  <child class="Layout.Widgets.FXMLWidget">
                    <id>c7461996-717e-460e-b32d-622d9290316f</id>
                    <name>Playlist</name>
                    <configs>
                      <Configuration.Config>
                        <gui__name>Is preferred</gui__name>
                        <name>preferred</name>
                        <value class="boolean">false</value>
                        <type>java.lang.Boolean</type>
                        <group>FXMLWidget</group>
                        <info>Preffered widget for its widget type.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Table orientation</gui__name>
                        <name>table_orient</name>
                        <value class="javafx.geometry.NodeOrientation">INHERIT</value>
                        <type>javafx.geometry.NodeOrientation</type>
                        <group>PlaylistController</group>
                        <info>Orientation of table.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Table text orientation</gui__name>
                        <name>cell_align</name>
                        <value class="javafx.geometry.Pos">CENTER_LEFT</value>
                        <type>javafx.geometry.Pos</type>
                        <group>PlaylistController</group>
                        <info>Orientation of text within table cells.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Zeropad numbers</gui__name>
                        <name>zeropad</name>
                        <value class="boolean">false</value>
                        <type>java.lang.Boolean</type>
                        <group>PlaylistController</group>
                        <info>Adds 0 to uphold number length consistency.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Show table menu button</gui__name>
                        <name>show_menu_button</name>
                        <value class="boolean">true</value>
                        <type>java.lang.Boolean</type>
                        <group>PlaylistController</group>
                        <info>Show table menu button for controlling columns.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Show table header</gui__name>
                        <name>show_header</name>
                        <value class="boolean">true</value>
                        <type>java.lang.Boolean</type>
                        <group>PlaylistController</group>
                        <info>Show table header with columns.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Search show always</gui__name>
                        <name>always_show_search</name>
                        <value class="boolean">false</value>
                        <type>java.lang.Boolean</type>
                        <group>PlaylistController</group>
                        <info>Forbid hiding of the search paneat all times. It will always be displayed.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Search hide always</gui__name>
                        <name>always_hide_search</name>
                        <value class="boolean">false</value>
                        <type>java.lang.Boolean</type>
                        <group>PlaylistController</group>
                        <info>Allows hiding search pane even if in effect.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Search ignore case</gui__name>
                        <name>ignoreCase</name>
                        <value class="boolean">true</value>
                        <type>java.lang.Boolean</type>
                        <group>PlaylistController</group>
                        <info>Ignore case when comparing for search results.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                      <Configuration.Config>
                        <gui__name>Search show original index</gui__name>
                        <name>orig_index</name>
                        <value class="boolean">true</value>
                        <type>java.lang.Boolean</type>
                        <group>PlaylistController</group>
                        <info>Show index of the itme as it was in the unfiltered playlisteven when filter applied.</info>
                        <editable>true</editable>
                        <visible>true</visible>
                        <min>NaN</min>
                        <max>NaN</max>
                      </Configuration.Config>
                    </configs>
                  </child>
                </Layout.UniContainer>
              </entry>
            </children>
          </child>
        </Layout.UniContainer>
      </entry>
    </children>
  </child>
</Layout.Layout>