<GUI.Window>
  <W>1763.0</W>
  <H>41.0</H>
  <X>-9.0</X>
  <Y>0.0</Y>
  <minimized>false</minimized>
  <maximized>NONE</maximized>
  <fullscreen>false</fullscreen>
  <resizable>true</resizable>
</GUI.Window>