<GUI.Window>
  <W>1919.0</W>
  <H>43.0</H>
  <X>0.0</X>
  <Y>0.0</Y>
  <minimized>false</minimized>
  <maximized>NONE</maximized>
  <fullscreen>false</fullscreen>
  <resizable>false</resizable>
  <resizable>false</resizable>
</GUI.Window>